### ISSUE TITLE
Navigation bar styles on about page

### ISSUE THREAD

**Issue by adjeim** [DevinJakubowicz/ACCT#1]
The main page has the red bar behind the navigation, but the adopt page doesn't have that. Maybe add the red bar to the adopt page? (Alternatively, we could remove the bar altogether.)

**Comment by adjeim** [comment]
Specifically, line 14 of index.html has <span class="take-action">, but the nav on the about.html page is missing that.

**Comment by DevinJakubowicz** [comment]
wouldnt that close it? dont know why it didnt
